#' Create Minimal Synthetic HLA Genotype Test Data
#'
#' Generates a small hard-coded dataset representing HLA genotype information
#' across two loci (A and B) for five individuals. The data is intended for
#' use in unit tests of haplotype inference functions.
#'
#' @return A data.frame with columns: ID, A_1, A_2, B_1, B_2
#' @examples
#' create_mini_test_data()
#' @keywords internal
create_mini_test_data <- function() {
  test_data <- data.frame(
    ID = c("S1", "S2", "S3", "S4", "S5"),
    A_1 = c("A*01:01", "A*02:01", "A*03:01", "A*01:01", "A*02:01"),
    A_2 = c("A*02:01", "A*03:01", "A*24:02", "A*11:01", "A*24:02"),
    B_1 = c("B*07:02", "B*08:01", "B*15:01", "B*07:02", "B*35:01"),
    B_2 = c("B*08:01", "B*44:02", "B*35:01", "B*44:02", "B*44:02"),
    stringsAsFactors = FALSE
  )
  return(test_data)
}

#' Prepare Synthetic Genotype Data for Testing
#'
#' Takes test data generated by `create_mini_test_data()` and formats it
#' into genotype strings (e.g., A_1/A_2) for two loci. Also returns a list of loci.
#'
#' @return A list with elements:
#' \describe{
#'   \item{test_data}{original expanded genotype data}
#'   \item{genotypes}{collapsed per-locus genotype strings}
#'   \item{loci}{character vector of included loci}
#' }
#' @examples
#' prepare_test_data()
#' @keywords internal
prepare_test_data <- function() {
  test_data <- create_mini_test_data()
  loci <- c("A", "B")
  genotypes <- data.frame(
    ID = test_data$ID,
    A = paste(test_data$A_1, test_data$A_2, sep = "/"),
    B = paste(test_data$B_1, test_data$B_2, sep = "/"),
    stringsAsFactors = FALSE
  )
  return(list(
    test_data = test_data,
    genotypes = genotypes,
    loci = loci
  ))
}

test_that("standardize_colnames works", {
  # Create test data with non-standard column names
  test_df <- data.frame(
    ID = c("S1", "S2"),
    "A.1" = c("A*01:01", "A*02:01"),
    "A.2" = c("A*02:01", "A*03:01"),
    "B-1" = c("B*07:02", "B*08:01"),
    "B-2" = c("B*08:01", "B*44:02"),
    stringsAsFactors = FALSE
  )

  # Run function
  result <- standardize_colnames(test_df, quiet = TRUE)

  # Check results - column names should be standardized
  expect_true(all(c("A_1", "A_2", "B_1", "B_2") %in% names(result)))
  expect_false(any(c("A.1", "A.2", "B-1", "B-2") %in% names(result)))
})

test_that("extract_loci works", {
  # Create test data
  test_df <- data.frame(
    ID = c("S1", "S2"),
    A_1 = c("A*01:01", "A*02:01"),
    A_2 = c("A*02:01", "A*03:01"),
    B_1 = c("B*07:02", "B*08:01"),
    B_2 = c("B*08:01", "B*44:02"),
    DRB1_1 = c("DRB1*01:01", "DRB1*03:01"),
    DRB1_2 = c("DRB1*04:01", "DRB1*07:01"),
    stringsAsFactors = FALSE
  )

  # Run function
  result <- extract_loci(test_df, quiet = TRUE)

  # Check results
  expect_equal(sort(result), c("A", "B", "DRB1"))
})

test_that("collapse_genotypes works", {
  prep <- prepare_test_data()

  # Extract loci from standard data format
  loci <- c("A", "B")

  # Test collapsing - explicitly set isFamily=FALSE
  genotypes <- collapse_genotypes(prep$test_data, loci, quiet = TRUE, isFamily = FALSE)

  # Check result structure
  expect_equal(nrow(genotypes), nrow(prep$test_data))
  expect_true(all(c("ID", "A", "B") %in% names(genotypes)))

  # Check first row
  expect_equal(genotypes$A[1], "A*01:01/A*02:01")
  expect_equal(genotypes$B[1], "B*07:02/B*08:01")
})

test_that("enumerate_diplotypes works", {
  prep <- prepare_test_data()

  # Test with first sample
  first_sample <- prep$genotypes[1, , drop = FALSE]
  diplotypes <- enumerate_diplotypes(first_sample, quiet = TRUE)

  # Check basic structure
  expect_true(is.list(diplotypes))
  expect_equal(length(diplotypes), 2) # 2^(n-1) where n=2 loci
  # Replace sapply() with vapply() here:
  expect_true(all(vapply(diplotypes, function(d) all(c("hap1", "hap2") %in% names(d)), logical(1))))


  # Check that all alleles are present across all diplotypes
  all_haps <- unlist(lapply(diplotypes, function(d) c(d$hap1, d$hap2)))
  expect_true(all(c("A*01:01", "A*02:01", "B*07:02", "B*08:01") %in%
    unlist(strsplit(paste(all_haps, collapse = " "), "[^A-Z0-9*:]+"))))

  # Check that we have both possible combinations
  patterns <- c(
    # A*01:01 and B*07:02 in same haplotype
    vapply(diplotypes, function(d) {
      grepl("A\\*01:01", d$hap1) && grepl("B\\*07:02", d$hap1) ||
        grepl("A\\*01:01", d$hap2) && grepl("B\\*07:02", d$hap2)
    }, logical(1)),
    # A*02:01 and B*08:01 in same haplotype
    vapply(diplotypes, function(d) {
      grepl("A\\*02:01", d$hap1) && grepl("B\\*08:01", d$hap1) ||
        grepl("A\\*02:01", d$hap2) && grepl("B\\*08:01", d$hap2)
    }, logical(1))
  )
  expect_true(any(patterns))
})

test_that("compute_posteriors works", {
  # Set up sample diplotypes
  diplotypes <- list(
    list(
      list(hap1 = "A*01:01~B*07:02", hap2 = "A*02:01~B*08:01"),
      list(hap1 = "A*01:01~B*08:01", hap2 = "A*02:01~B*07:02")
    )
  )

  # Set frequencies where first combination is more common
  freqs <- c(0.4, 0.3, 0.2, 0.1)
  names(freqs) <- c("A*01:01~B*07:02", "A*02:01~B*08:01", "A*01:01~B*08:01", "A*02:01~B*07:02")

  # Compute posteriors
  posteriors <- compute_posteriors(diplotypes, freqs, quiet = TRUE)

  # Check structure
  expect_equal(length(posteriors), length(diplotypes))
  expect_equal(length(posteriors[[1]]), 2)

  # First diplotype should have higher probability (0.4*0.3 vs 0.2*0.1)
  # P(diplotype1) = 0.4*0.3/norm, P(diplotype2) = 0.2*0.1/norm
  # norm = 0.4*0.3 + 0.2*0.1
  # Expect diplotype1 to have higher probability
  expect_true(posteriors[[1]][1] > posteriors[[1]][2])

  # Posteriors should sum to 1
  expect_equal(sum(posteriors[[1]]), 1, tolerance = 1e-6)
})

test_that("run_em_algorithm works with synthetic data", {
  prep <- prepare_test_data()

  # Enumerate diplotypes for each sample
  all_diplotypes <- list()
  for (i in seq_len(nrow(prep$genotypes))) {
    all_diplotypes[[i]] <- enumerate_diplotypes(prep$genotypes[i, , drop = FALSE], quiet = TRUE)
  }

  # Run EM algorithm with limited iterations for testing
  freqs <- run_em_algorithm(
    all_diplotypes,
    max_iter = 10,
    epsilon = 1e-4,
    quiet = TRUE
  )

  # Check basic properties
  expect_true(is.numeric(freqs))
  expect_true(all(freqs >= 0))
  expect_true(all(freqs <= 1))
  expect_equal(sum(freqs), 1, tolerance = 1e-6)
  expect_true(!is.null(names(freqs)))

  # Check convergence info
  expect_false(is.null(attr(freqs, "converged")))
  expect_false(is.null(attr(freqs, "iterations")))

  # The number of unique haplotypes should be reasonable
  # With 5 samples, 2 loci, 2 alleles each, max would be 2*2 = 4 haplotypes
  expect_true(length(freqs) <= 4 * 4) # Upper bound estimate
})

test_that("infer_haplotypes works with synthetic data", {
  # Create test data
  test_data <- create_mini_test_data()

  # Run the full inference pipeline
  results <- infer_haplotypes(
    df = test_data,
    loci = c("A", "B"),
    parallel = FALSE,
    quiet = TRUE,
    isFamily = FALSE # Explicitly set to FALSE to avoid warning
  )

  # Check results structure
  expect_true(is.list(results))
  expect_true(all(c(
    "haplotype_frequencies",
    "top_diplotypes",
    "posteriors",
    "loci_used",
    "convergence",
    "iterations"
  ) %in% names(results)))

  # Check haplotype frequencies
  hap_freqs <- results$haplotype_frequencies$frequency
  expect_equal(sum(hap_freqs), 1, tolerance = 1e-6)

  # Check that all samples have a top diplotype assigned
  expect_equal(nrow(results$top_diplotypes), 5)

  # Check that loci were correctly identified
  expect_equal(sort(results$loci_used), c("A", "B"))
})
